version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${PGUSER}
      - SPRING_DATASOURCE_PASSWORD=${PGPASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
