version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://junction.proxy.rlwy.net:21560/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hXAsxzOiuMkSSfIpJHMPUeZOPrjhiYSz
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hXAsxzOiuMkSSfIpJHMPUeZOPrjhiYSz
      - "5432:5432"
